### ISSUE TITLE
porting to .net core?

### ISSUE THREAD

**Issue by austanss** [thomdixon/SaltwaterTaffy#6]
hi what are the .net framework dependent features what do i remove/add to port this to .net standard?

**Comment by thomdixon** [comment]
Honestly, I'm not sure. I haven't been keeping up with the changes in the .NET community since I left the Windows shop that I worked at when I first wrote this library, some 7 or so years ago. From my brief research, I don't really use anything in this library that shouldn't work in .NET Core. That being said, I do rely on [ `Simple.DotNMap.dll`](https://archive.codeplex.com/?p=dotnmap), which could probably be replaced at some point, and might not work on various systems.
